name: Branch Monitor

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'GitHub issue number to update with branch status'
        required: true
        type: number

concurrency:
  group: branch-monitor-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: read
    timeout-minutes: 60

    steps:
      - name: Monitor Branch Status
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = process.env.GITHUB_REF_NAME;
            const issueNumber = ${{ inputs.issue_number }};

            if (!branchName) {
              console.log('ERROR: GITHUB_REF_NAME environment variable is not set. Branch name is required.');
              process.exit(1);
            }

            if (!issueNumber) {
              console.log('ERROR: issue_number input is required.');
              process.exit(1);
            }

            const currentJobName = process.env.GITHUB_JOB;
            const COMMENT_MARKER = '<!-- branch-monitor-failure-comment -->';
            const POLL_INTERVAL = 30; // seconds
            const MAX_POLLS = 120; // 60 minutes total

            // Get commit data from the push event
            const commitSha = context.sha;
            const commitUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${commitSha}`;
            const commitMessage = context.payload.head_commit.message;
            const commitAuthor = context.payload.head_commit.author.username 
              ? `@${context.payload.head_commit.author.username}` 
              : context.payload.head_commit.author.name;
            const commitDate = context.payload.head_commit.timestamp;
            console.log(JSON.stringify(context, null, 2));

            console.log(`GITHUB_WORKFLOW: ${process.env.GITHUB_WORKFLOW}`);
            console.log(`GITHUB_RUN_ID: ${process.env.GITHUB_RUN_ID}`);
            console.log(`Monitoring checks for commit ${commitSha} on branch ${branchName}`);

            // Get required status checks from branch protection
            let requiredChecks = [];
            try {
              const { data: branchProtection } = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branchName
              });
              
              if (branchProtection.required_status_checks) {
                requiredChecks = branchProtection.required_status_checks.contexts || [];
                console.log(`Found ${requiredChecks.length} required status checks:`, requiredChecks);
              } else {
                console.log('No required status checks configured in branch protection');
              }
            } catch (error) {
              if (error.status === 404) {
                console.log('No branch protection configured');
              } else {
                console.log(`ERROR: Could not fetch branch protection (${error.status}): ${error.message}`);
                process.exit(1);
              }
            }

            // Poll for check completion
            let polls = 0;
            let overallStatus = 'pending';

            if (requiredChecks.length === 0) {
              console.log('No required status checks to monitor - treating as success.');
              overallStatus = 'success';
            }

            while (polls < MAX_POLLS && requiredChecks.length > 0) {
              polls++;
              console.log(`Poll ${polls}/${MAX_POLLS} - checking status...`);

              // Get combined status (external checks like CircleCI)
              const { data: combinedStatus } = await github.rest.repos.getCombinedStatusForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commitSha
              });

              // Get check runs (GitHub Actions and modern checks)
              const { data: checks } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commitSha,
                per_page: 100
              });

              // Combine into single array with normalized structure
              const allChecks = [
                // External statuses
                ...combinedStatus.statuses.map(status => ({
                  name: status.context,
                  state: status.state,
                  type: 'status'
                })),
                // GitHub check runs
                ...checks.check_runs.map(check => ({
                  name: check.name,
                  state: check.conclusion || check.status,
                  type: 'check'
                }))
              ];

              console.log(`Found ${allChecks.length} total checks for commit ${commitSha}`);
              allChecks.forEach(check => {
                console.log(`- ${check.type}: ${check.name}: ${check.state}`);
              });

              // Filter to only required checks
              const requiredCheckResults = allChecks.filter(check => requiredChecks.includes(check.name));
              
              console.log(`Found ${requiredCheckResults.length}/${requiredChecks.length} required checks`);
              requiredCheckResults.forEach(check => {
                console.log(`- Required: ${check.name}: ${check.state}`);
              });

              if (requiredCheckResults.length === 0) {
                console.log('No required checks found yet, continuing to poll...');
                await new Promise(resolve => setTimeout(resolve, POLL_INTERVAL * 1000));
                continue;
              }

              // Check if all required checks are completed
              const requiredStates = requiredCheckResults.map(check => check.state);
              const completedStates = requiredStates.filter(s => 
                s === 'success' || s === 'failure' || s === 'error' || s === 'cancelled' || s === 'timed_out' || s === 'skipped'
              );
              const allRequiredCompleted = completedStates.length === requiredChecks.length;

              console.log(`Completed: ${completedStates.length}/${requiredChecks.length} required checks`);
              console.log(`All required checks completed: ${allRequiredCompleted}`);

              if (allRequiredCompleted) {
                // Determine overall status from completed required checks only
                if (completedStates.every(s => s === 'success' || s === 'skipped')) {
                  overallStatus = 'success';
                } else if (completedStates.some(s => s === 'failure' || s === 'timed_out' || s === 'cancelled' || s === 'error')) {
                  overallStatus = 'failure';
                } else {
                  overallStatus = 'success'; // fallback
                }
                console.log(`All required checks completed with overall status: ${overallStatus}`);
                break;
              } else {
                console.log(`Still waiting for more required checks to complete, waiting ${POLL_INTERVAL}s...`);
                await new Promise(resolve => setTimeout(resolve, POLL_INTERVAL * 1000));
              }
            }

            if (polls >= MAX_POLLS) {
              console.log('Timeout reached, using current status');
              overallStatus = 'timeout';
            }

            // Generate status display
            const statusEmojis = {
              success: '✅',
              failure: '❌',
              timeout: '⏰',
              pending: '⏳'
            };

            const emoji = statusEmojis[overallStatus] || '❓';
            const shortSha = commitSha.substring(0, 7);
            const date = new Date(commitDate).toISOString();

            const issueTitle = `Status Monitor for the \`${branchName}\` branch`;
            const issueBody = `<!-- This issue is automatically updated by the branch-monitor workflow. Do not edit manually as changes will be overwritten. -->

            This issue automatically tracks the CI status of the \`${branchName}\` branch. It monitors all checks and updates whenever new commits are pushed.

            **Latest Commit**: [\`${shortSha}\`](${commitUrl}) ${commitMessage.split('\n')[0]} ${emoji} **${overallStatus}**

            ---
            *Last updated: ${new Date().toISOString()}*`;

            // Update issue title and body
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              title: issueTitle,
              body: issueBody
            });

            console.log(`Updated issue #${issueNumber} with status: ${overallStatus}`);

            // Handle failure comments
            const hasFailure = overallStatus === 'failure';

            // Get existing comments
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

            const existingFailureComment = comments.find(comment => 
              comment.body.includes(COMMENT_MARKER)
            );

            if (hasFailure && !existingFailureComment) {
              // Post failure comment
              const failureComment = `${COMMENT_MARKER}
            🚨 **Build Failure Detected**

            The latest commit on branch \`${branchName}\` has failed checks:
            - **Commit**: [\`${shortSha}\`](${commitUrl})
            - **Message**: ${commitMessage.split('\n')[0]}
            - **Author**: ${commitAuthor}

            Please investigate and fix the failing checks.`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: failureComment
              });

              console.log('Posted failure comment');
            } else if (!hasFailure && existingFailureComment) {
              // Remove failure comment when status is green
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingFailureComment.id
              });

              console.log('Removed failure comment - status is now green');
            }
