name: Monitor Test Branch

on:
  push:
    branches: ['test-monitor']

env:
  ISSUE_NUMBER: ${{ vars.MONITOR_ISSUE_NUMBER }}

jobs:
  monitor:
    uses: ./.github/workflows/branch-monitor.yml
    with:
      issue_number: ${{ vars.MONITOR_ISSUE_NUMBER }}