name: Monitor Test Branch

on:
  push:
    branches: ['test-monitor']

jobs:
  monitor:
    uses: ./.github/workflows/branch-monitor.yml
    permissions:
      issues: write
      checks: read
    with:
      issue_number: 1
